### ISSUE TITLE
This function is essential?

### ISSUE THREAD

**Issue by Juddd** [szhorvat/Spelunking#6]
Why not use ``GeneralUtilities`PrintDefinitionsLocal[RunThrough]`` directly?

**Comment by Juddd** [comment]
![image](https://user-images.githubusercontent.com/10048069/180002228-2f3a45b6-5ee6-4661-8833-bfe2f53d8898.png)

**Comment by szhorvat** [comment]
This package was written long before ``GeneralUtilities`PrintDefinitions[]`` became available. I suggest you simply use ``GeneralUtilities`PrintDefinitions[]``.

**Comment by Juddd** [comment]
You just updated it 9 days ago, so I have this question

**Comment by szhorvat** [comment]
It was 9 years ago, not 9 days ago :-)

**Comment by Juddd** [comment]
Oh, god my English reading....
